### ISSUE TITLE
Plugin no longer appears in Runelite for me

### ISSUE THREAD

**Issue by dmattia** [Flipping-Utilities/rl-plugin#20]
I no longer see an Icon for FlippingUtilities after using for quite a while.

I cannot find the plugin in the external plugin search:

<img width="243" alt="Screen Shot 2022-06-29 at 10 56 59 AM" src="https://user-images.githubusercontent.com/8922077/176481935-5b812d9d-0361-4238-92d5-1e2214386122.png">

And also no longer have it in my installed plugins:

<img width="240" alt="Screen Shot 2022-06-29 at 10 57 53 AM" src="https://user-images.githubusercontent.com/8922077/176482048-5a4e8840-9f8d-437a-9abb-116a9b372c6b.png">

**Comment by Kaybuh** [comment]
I am having the same issues. It's as if it doesn't exist within Runelite anymore? Commenting to hopefully get some answers as well!

**Comment by AntonyGarand** [comment]
This is a known issue: The latest runelite release changed the API and broke some plugins including ours.
You can follow the fix status on this PR: https://github.com/runelite/plugin-hub/pull/2915

**Comment by zumaad** [comment]
its back up!
