### ISSUE TITLE
[Request] Allow sidebar to pop out into separate menu

### ISSUE THREAD

**Issue by jevonsp** [Flipping-Utilities/rl-plugin#22]
I play on a relatively small resolution and the sidebar can get quite cramped.

When you make a recipe, it pops out into another window. Is it possible to pop the entire sidebar into another window to make the real estate for the plugin bigger? 

Thanks so much if you read this, absolutely love the plugin :)

**Comment by zumaad** [comment]
Thanks for the kind words! As for the pop out suggestion, unfortunately there are a bunch of complications with doing that properly that make it unlikely for us to pursue :(
