### ISSUE TITLE
Feature request: allow adding arbitrary cost to recipe flips

### ISSUE THREAD

**Issue by itssapir** [Flipping-Utilities/rl-plugin#31]
Sometimes recipes take a few ingredients that aren't calculated in the plugin.
An example of this is making a bofa costing crystal shards. (and the amount varies as well)
These items are not bought at the g.e (atleast not directly), but do have some value.
Instead of asking you to try and add these on a per recipe basis, I think a simple solution would be to allow
the addition of "Extra recipe costs in gp" to the recipe, which would be deducted from the final profit.

in the crystal seed example, lets say I used 100 shards that I got by trading in a teleport crystal, which puts the value at slightly over 10k each, I would add 1m or so to the recipe costs, and get more accurate data.

**Comment by zumaad** [comment]
Thanks for adding this feature!
